services:
  backend:
    build: ./backend
    ports: 
      - 4000:4000
    volumes:
      - /app/db
      - ./backend/src:/app/src
    env_file: ./backend/.env
  db:
    image: postgres
    ports: 
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    env_file: .env
  adminer: 
    image: adminer
    restart: always
    ports:
      - 8888:8080
#  frontend:
#   build: ./frontend
#    command: npm run dev
#    ports: 
#      - 3000:3000
#    volumes:
#      - ./frontend/src:/app/src